// Simple environment configuration without T3 validation for better build performance
export const env = {
  NEXT_PUBLIC_TURNKEY_API_BASE_URL: process.env.NEXT_PUBLIC_TURNKEY_API_BASE_URL || 'https://api.turnkey.com',
  NEXT_PUBLIC_TURNKEY_ORGANIZATION_ID: process.env.NEXT_PUBLIC_TURNKEY_ORGANIZATION_ID || '',
  NEXT_PUBLIC_TURNKEY_RP_ID: process.env.NEXT_PUBLIC_TURNKEY_RP_ID || 'localhost',
  NEXT_PUBLIC_TURNKEY_AUTH_IFRAME_URL: process.env.NEXT_PUBLIC_TURNKEY_AUTH_IFRAME_URL,
  NEXT_PUBLIC_TURNKEY_EXPORT_IFRAME_URL: process.env.NEXT_PUBLIC_TURNKEY_EXPORT_IFRAME_URL,
  NEXT_PUBLIC_TURNKEY_IMPORT_IFRAME_URL: process.env.NEXT_PUBLIC_TURNKEY_IMPORT_IFRAME_URL,
  ALCHEMY_API_KEY: process.env.ALCHEMY_API_KEY,
}